import assert from 'assert'
import fs from 'fs'
import path from 'path'

const sourceRoot = path.resolve(__dirname)
const agentsSource = fs.readFileSync(path.join(sourceRoot, 'pages/Agents.tsx'), 'utf8')
const workflowsSource = fs.readFileSync(path.join(sourceRoot, 'pages/Workflows.tsx'), 'utf8')
const workflowDagSource = fs.readFileSync(path.join(sourceRoot, 'components/WorkflowDAG.tsx'), 'utf8')
const agentDetailSource = fs.readFileSync(path.join(sourceRoot, 'components/AgentDetailPanel.tsx'), 'utf8')
const pluginRelationshipSummarySource = fs.readFileSync(path.join(sourceRoot, 'components/PluginRelationshipSummary.tsx'), 'utf8')
const appSource = fs.readFileSync(path.join(sourceRoot, 'App.tsx'), 'utf8')
const pluginPageSource = fs.readFileSync(path.join(sourceRoot, 'pages/PluginWorkspacePage.tsx'), 'utf8')
const lifecycleEvidenceSource = fs.readFileSync(path.join(sourceRoot, 'components/AgentLifecycleEvidence.tsx'), 'utf8')
const evalGraphSource = fs.readFileSync(path.join(sourceRoot, 'lib/evalGraph.ts'), 'utf8')
const repoRoot = path.resolve(sourceRoot, '../../../..')
const manifests = [
  'PLUGINS/test/plugin-guardrails/clawmax-plugin.json',
  'PLUGINS/test/plugin-evals/clawmax-plugin.json',
  'PLUGINS/test/plugin-resource-plans/clawmax-plugin.json',
  'PLUGINS/public/clawmax-lifecycle/clawmax-plugin.json',
  'PLUGINS/public/clawmax-review/clawmax-plugin.json',
].map((relativePath) => JSON.parse(fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')))

assert(
  agentsSource.includes('costTrackingEnabled = true, relationships = []'),
  'Agent cards must receive a safe plugin relationship default',
)
assert(
  (agentsSource.match(/relationships=\{pluginRelationships\.agents\[agent\.id\] \|\| \[\]\}/g) || []).length >= 5,
  'Every agent card rendering path must receive plugin relationships',
)
assert(agentsSource.includes('pluginRelationships={pluginRelationships.agents[selectedAgent.id] || []}'), 'Agent detail must receive its complete plugin relationships')
assert(agentDetailSource.includes('<PluginRelationshipDetails relationships={pluginRelationships} />'), 'Agent detail must list attached plugin items')
assert(workflowsSource.includes('<PluginRelationshipDetails relationships={pluginRelationships.workflows[selectedWorkflow.id] || []} />'), 'Workflow detail must list attached plugin items')
assert((workflowsSource.match(/PluginRelationshipPills/g) || []).length >= 3, 'Workflow grid and table views must show compact plugin relationship pills')
assert(workflowDagSource.includes('pluginRelationships[wf.id] || []'), 'Workflow relationship nodes must show compact plugin activity')
assert(pluginRelationshipSummarySource.includes('+{overflowCount}'), 'Compact plugin relationships must collapse overflow into a discrete count pill')
assert(appSource.includes('h-[100dvh] max-h-[100dvh]'), 'The mobile sidebar must fit the dynamic viewport')
assert(appSource.includes('h-[100dvh] w-full min-w-0 overflow-hidden'), 'The app shell must not widen past the phone viewport')
assert(appSource.includes('function ChecklistIcon'), 'Release Review must have a checklist navigation icon')
assert(appSource.includes("plugin.objectKind === 'optimization-plan'"), 'Optimize must have a distinct activity navigation icon')
assert(pluginPageSource.includes("viewMode === 'grid' ? ("), 'Plugin content must render a compact grid view')
assert(pluginPageSource.includes("viewMode === 'detail' ? ("), 'Plugin content must render a detail view')
assert(pluginPageSource.includes("viewMode === 'graph' ? ("), 'Plugin content must render a relationship view')
assert(pluginPageSource.includes('selectedSuggestedTemplateId'), 'Suggested items must expose inspectable details')
assert(pluginPageSource.includes('heading="Suggested item"'), 'Suggested relationship views must identify their own records')
assert(pluginPageSource.includes("type PluginCollectionTab = 'active' | 'archived' | 'suggested'"), 'Suggested entries must live in a separate collection tab')
assert(pluginPageSource.includes('Suggested ({recommendedTemplates.length})'), 'The Suggested tab must show its available entry count')
assert(pluginPageSource.includes("collectionTab === 'suggested' && ("), 'Suggested search and filter controls must render only inside the Suggested tab')
assert(pluginPageSource.includes('value={suggestionSort}'), 'Suggested entries must expose independent sorting')
assert(pluginPageSource.includes('suggestionTags'), 'Suggested entries must expose independent tag filters')
assert(pluginPageSource.includes('const usedTemplateIds = useMemo'), 'Permanent plugin catalogs must remain visible after a suggestion is used')
assert(pluginPageSource.includes("inUse ? 'In use' : 'Use'"), 'Used suggestions must be labeled instead of disappearing from the catalog')
assert(pluginPageSource.includes("setCollectionTab('active')"), 'Using a suggestion must return users to their active workspace entries')
assert(pluginPageSource.includes('const hasLoadedRef = useRef(false)'), 'Revisited plugin pages must retain rendered data during background refreshes')
assert(pluginPageSource.includes('const [contextRes, itemsRes, templatesRes] = await Promise.all(['), 'Plugin context, items, and suggestions must load in parallel')
assert(pluginPageSource.includes("forceTemplateRefresh ? '?refresh=1' : ''"), 'The explicit Refresh action must bypass the suggestion cache')
assert(pluginPageSource.includes('Actions <span className="text-xs">▾</span>'), 'Plugin refresh belongs in the standard Actions menu')
assert(appSource.includes('PLUGIN_NAV_ORDER_STORAGE_KEY'), 'Plugin navigation order must persist in the current browser')
assert(appSource.includes('handlePluginDragOver'), 'Plugin navigation items must support reordering')
assert(appSource.includes('PLUGIN_NAV_EXPANDED_STORAGE_KEY'), 'Plugin section expansion must persist in the current browser')
assert(appSource.includes('resolvePluginNavExpanded'), 'Plugin navigation must use the default-expanded persistence helper')
assert(appSource.includes('min-w-0 flex-1 overflow-auto overflow-x-hidden'), 'Plugin routes must not widen the mobile dashboard viewport')
assert(pluginPageSource.includes('max-w-2xl break-words text-sm leading-5'), 'Plugin descriptions must wrap into a readable multi-line measure')
assert(pluginPageSource.includes("localStorage.setItem(`clawmax-plugin-view-mode:${plugin.slug}`"), 'Plugin view selection must persist like core tabs')
assert(pluginPageSource.includes('history: []'), 'Suggested guardrails must normalize persistence-only history before preview')
assert(pluginPageSource.includes('runs: []'), 'Suggested evals must normalize persistence-only runs before preview')
assert(pluginPageSource.includes('fields: base.fields || {}'), 'Suggested generic plugins must normalize declarative fields before preview')
assert(pluginPageSource.includes('min-w-0 w-full sm:w-auto'), 'Plugin headers must stack without clipping on phone viewports')
assert(pluginPageSource.includes('grid w-full min-w-0 grid-cols-4 overflow-hidden rounded-lg border'), 'Plugin view controls must occupy four stable mobile columns')
assert(pluginPageSource.includes('max-w-full grid-cols-3 overflow-hidden'), 'Plugin collection tabs must remain within the mobile viewport')
assert(pluginPageSource.includes('whitespace-nowrap px-1.5 py-2 text-xs'), 'Plugin collection labels must stay compact and unbroken on mobile')
assert(pluginPageSource.includes('type="range"'), 'Generic plugin forms must render declared slider controls')
assert(pluginPageSource.includes('grid-cols-[minmax(0,1fr)_7rem]'), 'Slider controls must reserve stable mobile space for exact values')
assert(pluginPageSource.includes('normalizePluginNumericValue(schema, event.target.value)'), 'Slider and numeric inputs must share bounded normalization')
assert(pluginPageSource.includes('function OptimizeRelationshipGraph'), 'Optimize must render a purpose-built relationship graph')
assert(pluginPageSource.includes('function RelationshipZoomControls'), 'Relationship views must share workflow-style zoom controls')
assert(pluginPageSource.includes('aria-label="Relationship graph zoom controls"'), 'Relationship zoom controls must be accessible')
assert(pluginPageSource.split('<RelationshipZoomControls zoom={zoom} onChange={setZoom} />').length - 1 === 4, 'Guardrails, Evals, Optimize, and Lifecycle must all expose relationship zoom')
assert(pluginPageSource.includes('Optimization relationships'), 'Optimize graph must explain its plan relationships')
assert(pluginPageSource.includes('mt-2 flex min-h-5 flex-wrap gap-3 text-xs'), 'Optimize relationship legend must remain on a stable second row')
assert(pluginPageSource.includes('Test fixture catalog'), 'Synthetic product fixtures must explain why only the public sample catalog is visible')
assert(pluginPageSource.includes('Dimensions connect to saved plans'), 'Active Optimize graph must distinguish dimensions, saved plans, and targets')
assert(pluginPageSource.includes('aria-label="Optimize relationship graph"'), 'Optimize graph must expose an accessible label')
assert(pluginPageSource.includes("item.id.startsWith('suggested:') ? 'Suggested plan'"), 'Optimize graph must distinguish suggested plans from Active plans')
assert(pluginPageSource.includes('height={canvasHeight * zoom}'), 'Relationship graph height must track the explicit zoom level')
assert(pluginPageSource.includes('suggested plans preview their optimization dimensions'), 'Suggested Optimize graphs must explain placeholder targets')
assert(pluginPageSource.includes("title: 'Target and priority'"), 'Optimize editor must group target and priority controls')
assert(pluginPageSource.includes("title: 'Budgets'"), 'Optimize editor must group monthly and per-run budgets')
assert(pluginPageSource.includes("title: 'Quality and speed'"), 'Optimize editor must group semantic quality and duration gauges')
assert(pluginPageSource.includes('Tune with AI'), 'Optimize editor must expose an AI-assisted tuning panel')
assert(pluginPageSource.includes('applyOptimizeAssistantText'), 'Optimize AI assistance must apply structured changes to the current draft')
assert(pluginPageSource.includes('OPTIMIZE_AI_TUNING_EXPANDED_STORAGE_KEY'), 'Optimize AI tuning expansion must persist in the current browser')
assert(pluginPageSource.includes('lg:col-span-2'), 'Optimize AI tuning must occupy the full editor width above manual controls')
assert(pluginPageSource.includes('suggestionTemplates={filteredSuggestions}'), 'Suggested Optimize graphs must consume the visible suggestion templates directly')
assert(pluginPageSource.includes('Select {subjectType}'), 'Suggested Lifecycle relationships must expose a direct target-selection action')
assert(pluginPageSource.includes('onApplySuggestion(suggestion.id.replace(/^suggested:/, \'\'))'), 'Lifecycle target-selection action must open the edit inspection flow')
assert(pluginPageSource.includes('onApplySuggestion={(templateId) => void applyTemplate(templateId)}'), 'Lifecycle relationship suggestions must use the existing template apply and edit flow')
assert((pluginPageSource.match(/onApplySuggestion=\{\(templateId\) => void applyTemplate\(templateId\)\}/g) || []).length >= 2, 'Suggested and active Lifecycle relationship views must both wire the edit flow')
assert(pluginPageSource.includes('headerPrimaryButtonClass} px-2.5 py-1 text-xs'), 'Lifecycle target-selection action must retain the primary shortcut styling')
assert(pluginPageSource.includes('No suggested plans match the current search and filters.'), 'Suggested Optimize graphs must explain a genuinely empty filtered result')
assert(pluginPageSource.includes('aria-pressed={selectedId === item.id}'), 'Optimize graph plans must expose their locked selected state')
assert(pluginPageSource.includes("isMuted ? 'opacity-10'"), 'Optimize graph edges unrelated to the selected plan must be muted')
assert(pluginPageSource.includes('selectedDimensions.has(label)'), 'Optimize graph selection must emphasize applicable attributes')
assert(pluginPageSource.includes('selectedTargetKeys.has(key)'), 'Optimize graph selection must emphasize the applicable destination')
assert(pluginPageSource.includes('const [hoveredId, setHoveredId]'), 'Optimize graphs must track a temporary hover preview')
assert(pluginPageSource.includes('const emphasizedId = hoveredId || selectedId'), 'Hover previews must temporarily override the locked graph selection')
assert(pluginPageSource.includes("onMouseEnter={() => setHoveredId(item.id)}"), 'Optimize plan nodes must preview their relationships on hover')
assert(!pluginPageSource.includes('useInlineGraphDetails'), 'Active and Archived Optimize graph selections must retain the standard detail drawer')
assert(pluginPageSource.includes("{selectedItem && plugin.objectKind !== 'lifecycle-view' && ("), 'Selected Active and Archived records must open their detail drawer except when Lifecycle supplies its own X-ray')
assert(pluginPageSource.includes('function GuardrailRelationshipGraph'), 'Guardrails must render a purpose-built relationship graph')
assert(pluginPageSource.includes('Guardrail relationship graph'), 'Guardrail relationship graphs must expose an accessible label')
assert(pluginPageSource.includes('getGuardrailProtections'), 'Guardrail graphs must derive protection attributes from configured controls')
assert(pluginPageSource.includes('targetsFor(emphasizedGuardrail)'), 'Guardrail graph selection must emphasize assigned targets')
assert(pluginPageSource.includes('Hover to preview; click for full details.'), 'Active Guardrail graphs must explain hover and detail behavior')
assert(pluginPageSource.includes('Hover to inspect one before assigning agents or workflows.'), 'Suggested Guardrail graphs must explain assignment placeholders')
assert(pluginPageSource.includes('suggestionTemplates.map(templateToPreviewRecord).filter(isGuardrailRecord)'), 'Suggested Guardrail graphs must consume visible templates directly')
assert(pluginPageSource.includes('suggestionTemplates={suggestionTemplates}'), 'Guardrail relationship views must forward suggested templates to the graph')
assert(pluginPageSource.includes("const showingSuggestions = suggestionTemplates !== undefined"), 'Empty filtered Guardrail suggestions must retain suggested-graph semantics')
assert(!pluginPageSource.includes('is highlighted with the protections it applies'), 'Guardrail graph descriptions and legends must not move when selection changes')
assert(pluginPageSource.includes('GUARDRAIL_AI_CONFIG_EXPANDED_STORAGE_KEY'), 'Guardrail AI editor expansion must persist in the current browser')
assert(pluginPageSource.includes('Configure with AI'), 'Guardrail editors must expose AI-assisted draft configuration')
assert(pluginPageSource.includes('applyAiGuardrailChanges'), 'Guardrail AI assistance must update the current draft')
assert(pluginPageSource.includes('External action guidance'), 'Guardrail editors must group external-action guidance')
assert(pluginPageSource.includes('Approved skills'), 'Guardrail editors must separate approved skills from blocked actions')
assert(pluginPageSource.includes('Select the agents and workflows this advisory policy references.'), 'Guardrail editors must explain advisory assignments')
assert(pluginPageSource.includes('function EvalRelationshipGraph'), 'Evals must render a purpose-built relationship graph')
assert(pluginPageSource.includes('aria-label="Eval relationship graph"'), 'Eval relationship graphs must expose an accessible label')
assert(pluginPageSource.includes('suggestionTemplates.map(templateToPreviewRecord).filter(isEvalRecord)'), 'Suggested Eval graphs must consume visible templates directly')
assert(pluginPageSource.includes('planned trial'), 'Eval graph nodes must expose the planned experiment extent')
assert(pluginPageSource.includes('aria-label={`Run ${item.name}`}'), 'Enabled Eval graph nodes must expose a direct run action')
assert(pluginPageSource.includes('Running ${progressCompleted}/${progressTotal} cases'), 'Running Eval graph nodes must expose case progress')
assert(pluginPageSource.includes('item.lastRun.casesCompleted'), 'Completed Eval graph nodes must retain case completion evidence')
assert(pluginPageSource.includes('getEvalReadiness(item)'), 'Eval run actions must use shared readiness checks')
assert(pluginPageSource.includes('Needs setup · ${readiness.issues.length}'), 'Eval graph nodes must explain incomplete configurations')
assert(pluginPageSource.includes('onAssignTarget(target.id)'), 'Unassigned Eval graph targets must open target assignment')
assert(pluginPageSource.includes('focusEvalTargets={focusEvalTargets}'), 'Graph target assignment must focus the correct editor section')
assert(pluginPageSource.includes('Create or refresh Eval report'), 'Eval document actions must explain the generated artifact')
assert(pluginPageSource.includes('data.item?.document?.path && onNavigateToDoc'), 'Generated Eval reports must open after creation')
assert(pluginPageSource.includes('Send status notification'), 'Per-Eval notifications must use explicit status copy')
assert(pluginPageSource.includes("iconName=\"notification\""), 'Per-Eval status notifications must use a bell instead of chat')
assert(pluginPageSource.includes("iconName={item.enabled ? 'pause' : 'restart'}"), 'Plugin views must expose enable and disable controls')
assert(pluginPageSource.includes('function EvalScoreReviewDialog'), 'Completed Evals must expose a dedicated score review dialog')
assert(pluginPageSource.includes('aria-label={`Open ${item.name} score review`}'), 'Eval cards and graph nodes must expose the score review action')
assert(pluginPageSource.includes('Latest aggregate score'), 'Score review must distinguish the stored aggregate score')
assert(pluginPageSource.includes('Per-case scores will appear here when the evaluator runtime records them.'), 'Score review must not invent unavailable per-case evidence')
assert(pluginPageSource.includes('onOpenScore={setScoreReviewItemId}'), 'Eval relationship views must wire score review actions')
assert(pluginPageSource.includes("'Enabled' : 'Disabled'"), 'Plugin graph nodes must distinguish enabled and disabled records')
assert(evalGraphSource.includes('AI evaluator'), 'Eval graphs must identify AI evaluation')
assert(evalGraphSource.includes('Human evaluator'), 'Eval graphs must recognize human evaluation')
assert(evalGraphSource.includes('Fixed evaluator'), 'Eval graphs must identify fixed evaluation')
assert(pluginPageSource.includes('Attributes connect through each repeatable Eval'), 'Active Eval graphs must explain their experiment relationships')
assert(pluginPageSource.includes('suggested Evals preview their attributes, trial set, evaluator, and unassigned target'), 'Suggested Eval graphs must explain all preview stages')
assert(pluginPageSource.includes('Evaluation attributes connected to experiments, evaluators, and assigned targets'), 'Eval graph titles must describe the complete relationship')
assert(pluginPageSource.includes('No Evals match the current search and filters.'), 'Filtered Suggested Eval graphs must explain an empty result')
assert(pluginPageSource.includes('targetsFor(emphasizedEval)'), 'Eval graph selection must emphasize the applicable target')
assert(pluginPageSource.includes('EVAL_AI_CONFIG_EXPANDED_STORAGE_KEY'), 'Eval AI editor expansion must persist in the current browser')
assert(pluginPageSource.includes('applyAiEvalChanges'), 'Eval AI assistance must update the current draft')
assert(pluginPageSource.includes('Prefer AI for semantic evaluation'), 'Eval AI assistance must apply the evaluator selection policy')
assert(pluginPageSource.includes('Describe what to evaluate, how many trials to run'), 'Eval AI editor must explain its configuration scope')
assert(pluginPageSource.includes('Configure Eval'), 'Eval AI editing must expose a clear apply action')
assert(pluginPageSource.includes('Planned trials'), 'Eval manual editing must expose experiment extent')
assert(pluginPageSource.includes('<option value="human">Human evaluator</option>'), 'Eval manual editing must expose Human evaluation')
assert(pluginPageSource.includes('<option value="ai">AI evaluator (not yet runnable)</option>'), 'Eval editing must disclose that AI evaluation is not yet runnable')
assert(pluginPageSource.includes('Total executions across the configured case set.'), 'Eval trial controls must explain what is counted')
assert(pluginPageSource.includes('Find a ${evalTargetType} by name or ID'), 'Eval targets must expose searchable workspace choices')
assert(pluginPageSource.includes('visibleEvalTargetOptions.map'), 'Eval target search must render actual agents, workflows, or groups')
assert(pluginPageSource.includes('checked={selected}'), 'Eval targets must use direct checkbox selection')
assert(pluginPageSource.includes('AI evaluator prompt'), 'AI Eval editing must expose a judge prompt')
assert(pluginPageSource.includes('Advisory only: checked actions are recorded as policy intent'), 'Guardrail controls must disclose that they are not runtime enforcement')
assert(pluginPageSource.includes('Assignment does not enforce the policy at runtime'), 'Guardrail assignments must not imply active enforcement')
assert(!pluginPageSource.includes('Checked actions are blocked for every assigned target.'), 'Guardrail UI must not claim unenforced actions are blocked')
assert(!pluginPageSource.includes('Prevents assigned agents and workflows from sending email.'), 'Guardrail UI must not claim it intercepts outbound email')
assert(pluginPageSource.includes('Human reviewer instructions'), 'Human Eval editing must expose reviewer instructions')
assert(pluginPageSource.includes('Comparison rule'), 'Fixed Eval editing must expose a comparison rule')
assert(pluginPageSource.includes('Regular expression'), 'Fixed Eval editing must support regular-expression matching')
assert(pluginPageSource.includes('Case sensitive'), 'Fixed Eval editing must expose case sensitivity')
assert(pluginPageSource.includes('Default regular expression'), 'Fixed Eval editing must expose the default regular expression directly')
assert(pluginPageSource.includes('Suggest regex'), 'Fixed Eval editing must offer AI-assisted regular-expression generation')
assert(pluginPageSource.includes('validateEvalRegex'), 'Fixed Eval editing must validate regular expressions before use')
assert(pluginPageSource.includes('Reviewer email'), 'Human Eval editing must capture reviewer assignment metadata')
assert(pluginPageSource.includes('Review Markdown path'), 'Human Eval editing must expose the workspace review handoff path')
assert(pluginPageSource.includes('Email is assignment metadata only'), 'Human Eval editing must not imply that saving silently sends email')
assert(pluginPageSource.includes('define the rubric, priorities, evidence requirements'), 'AI evaluator prompts must explain useful rubric content')
assert(pluginPageSource.includes('function EvalCasesDialog'), 'Eval editing must provide a dedicated trial-case dialog')
assert(pluginPageSource.includes('Manage cases'), 'Eval editing must expose the trial-case manager')
assert(pluginPageSource.includes("(['input', 'expected'] as const)"), 'Each Eval trial case must configure both input and expected outcome')
assert(pluginPageSource.includes("(['text', 'file'] as const)"), 'Trial inputs and expected outcomes must support text or workspace files')
assert(pluginPageSource.includes("fetch('/api/docs')"), 'Eval workspace-file selection must use the existing document inventory')
assert(pluginPageSource.includes('its contents are not copied into this Eval'), 'Workspace file references must explain their privacy boundary')
assert(pluginPageSource.includes('zIndexClassName="z-[130]"'), 'The trial-case editor must remain above its parent Eval dialog')
assert(pluginPageSource.includes('from-rose-400 via-amber-300 to-emerald-400'), 'Quality controls must expose a low-to-high semantic gauge')
assert(pluginPageSource.includes('from-emerald-400 via-amber-300 to-rose-400'), 'Duration controls must expose a fast-to-slow semantic gauge')
assert((agentsSource.match(/const menuWidth = 224/g) || []).length >= 3, 'Agent action menus must reserve enough width for icon and Template labels')
assert(pluginPageSource.includes("setError(`Could not use this suggestion:"), 'Suggestion failures must be visible instead of becoming rejected click promises')
assert(pluginPageSource.includes("applying ? 'Adding...' : inUse ? 'In use' : 'Use'"), 'Suggestion actions must expose progress and in-use state')
assert(pluginPageSource.includes("applyingTemplateIds.has(template.id) ? 'Adding...' : usedTemplateIds.has(template.id) ? 'In use' : 'Use'"), 'Suggestion list actions must expose progress and in-use state')
assert(pluginPageSource.includes('formatPluginTargetNames(item, context)'), 'Plugin cards must list the concrete agents, workflows, or communication targets they affect')
assert(pluginPageSource.includes('Acts on'), 'Plugin detail cards must label concrete target relationships')
assert(lifecycleEvidenceSource.includes('Loading agent lifecycle...'), 'Lifecycle X-rays must show an explicit loading state while evidence is retrieved')
assert(appSource.includes('Review or revoke activity sharing'), 'The dashboard sharing pill must open a consent management popover')
assert(appSource.includes("/api/activity-export/consent"), 'The sharing popover must support revoking a destination')
assert(appSource.includes('Open sharing settings'), 'The sharing popover must link back to sharing settings')
assert(manifests.every((manifest) => !/dormant|test plugin|mvp/i.test(`${manifest.name} ${manifest.description} ${manifest.version}`)), 'Enabled plugin UI copy must be product-ready')
assert(new Set(manifests.map((manifest) => manifest.icon)).size === manifests.length, 'Each first-party plugin must declare a distinct navigation icon')

console.log('PluginWorkspaceLayout.test.ts: 152 tests passed')
