import fs from 'fs'
import path from 'path'

const repoRoot = path.resolve(__dirname, '../../../..')
const pluginRoot = path.join(repoRoot, 'PLUGINS/public/clawmax-review')
const manifest = JSON.parse(fs.readFileSync(path.join(pluginRoot, 'clawmax-plugin.json'), 'utf-8'))
const pageSource = fs.readFileSync(path.join(__dirname, 'pages/PluginWorkspacePage.tsx'), 'utf-8')
const checklistFiles = fs.readdirSync(path.join(pluginRoot, 'templates')).filter((file) => file.endsWith('.json')).sort()
const checklists = checklistFiles.map((file) => JSON.parse(fs.readFileSync(path.join(pluginRoot, 'templates', file), 'utf-8')))
const checklistByRelease = new Map(checklists.map((checklist) => [checklist.release, checklist]))
const stableChecklist = checklistByRelease.get('1.9.9 regression')
const previousChecklist = checklistByRelease.get('2.0.0 previous RCs')
const currentChecklist = checklistByRelease.get('2.0.0-test-rc45')
const allItems = checklists.flatMap((checklist) => checklist.items)

function assert(condition: boolean, message: string) {
  if (!condition) throw new Error(message)
}

assert(manifest.nav.label === 'Review', 'Review plugin must use a compact navigation label')
assert(manifest.visibility === 'public', 'Review must remain a public product plugin')
assert(manifest.enabledByDefault === true, 'Review must load in the public image by default')
assert(manifest.nav.order === 1000, 'Review must be the last plugin in the default navigation order')
assert(manifest.ui.list.groupBy === 'release', 'Review records must be compartmentalized by release')
assert(manifest.ui.list.checkField === 'completed', 'Review records must declare their completion checkbox')
assert(manifest.recordSchema.properties.verifiedBy?.type === 'array', 'Review records must support aggregated prior tester confirmation')
assert(JSON.stringify(manifest.recordSchema.properties.reviewReason?.enum) === JSON.stringify(['human-judgment', 'external-environment']), 'Review records must name the reason independent review is needed')
assert(checklistFiles.length === 3, 'Review must expose stable, cumulative, and current release sets')
assert(JSON.stringify(Array.from(checklistByRelease.keys()).sort()) === JSON.stringify(['1.9.9 regression', '2.0.0 previous RCs', '2.0.0-test-rc45']), 'Review set names must be stable and unambiguous')
assert(currentChecklist?.items.length === 6, 'Current RC45 must contain only the six checks requiring independent review')
assert(currentChecklist?.items.length <= 8, 'A focused release review must not become a substitute for the automated test suite')
assert(previousChecklist?.recommended === false, 'Previous RC criteria must remain historical instead of entering the reviewer queue')
assert(stableChecklist?.recommended === false, 'Stable-line criteria must remain historical instead of entering the reviewer queue')
assert(new Set(allItems.map((item: any) => item.id)).size === allItems.length, 'Checklist item IDs must not duplicate across review sets')
assert(new Set(allItems.map((item: any) => item.name.trim().toLowerCase().replace(/\s+/g, ' '))).size === allItems.length, 'Checklist names must not duplicate across review sets')
assert(allItems.every((item: any) => /^Test:\s*.+\s+Pass:\s*.+$/i.test(item.description)), 'Every check must provide explicit Test and Pass instructions')
assert(currentChecklist?.items.every((item: any) => !/\b1\)/.test(item.description)), 'Current checks must use plain instructions instead of dense numbered procedures')
assert(currentChecklist?.items.every((item: any) => item.description.length <= 500), 'Current checks must stay concise enough for non-expert testers')
assert(allItems.every((item: any) => item.fields.notes === ''), 'New checklist notes must start empty and visually neutral')
assert(checklists.every((checklist) => checklist.defaults.fields.completed === false), 'Every review set must start unchecked')
assert(checklists.every((checklist) => checklist.defaults.fields.outcome === 'pending'), 'Every review set must start pending')
assert(checklists.every((checklist) => Array.isArray(checklist.defaults.fields.verifiedBy)), 'Every review set must initialize prior verification metadata')
assert(currentChecklist?.items.every((item: any) => ['human-judgment', 'external-environment'].includes(item.fields.reviewReason)), 'Every current check must justify independent review')
assert(currentChecklist?.items.every((item: any) => !/\/api\/health|\/api\/system|catalog contains|CI build|unit test|integration test/i.test(item.description)), 'Deterministic release gates must stay out of the human review queue')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc45-builder-create-and-chat'), 'Current RC must independently review the repaired Builder creation journey')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc45-partner-and-skill-boundaries'), 'Current RC must independently review partner and skill clarity')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc45-lmstudio-gemma-chat'), 'Current RC must independently run the reported LM Studio model')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc45-qbo-runtime-install'), 'Current RC must independently run QBO on both image architectures')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc45-resource-retention-soak'), 'Current RC must retain the external resource-soak launch gate')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc39-agent-discovery-and-details'), 'Previous RC history must preserve superseded RC39 criteria')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc38-persistent-session-recovery'), 'Cumulative checks must preserve superseded RC38 criteria')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc24-private-cloud-bundle'), 'Cumulative checks must retain RC24 private bundle coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc24-relationship-zoom'), 'Cumulative checks must retain RC24 relationship zoom')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc24-plugin-compound-discovery'), 'Cumulative checks must retain RC24 compound discovery')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc24-builder-question'), 'Cumulative checks must retain RC24 Builder question mode')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc23-private-catalog-upgrade'), 'Cumulative checks must retain RC23 private catalog coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc22-release-identity-and-catalogs'), 'Cumulative checks must retain complete RC22 catalog coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc22-eval-run-controls-and-case-progress'), 'Cumulative checks must retain RC22 Eval run coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc21-guardrail-complete-flow'), 'Cumulative checks must retain the complete RC21 Guardrail flow')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc21-eval-complete-flow'), 'Cumulative checks must retain the complete RC21 Eval flow')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc21-optimize-complete-flow'), 'Cumulative checks must retain the complete RC21 Optimize flow')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc18-auto-model-settings-persist'), 'Cumulative checks must retain RC18 per-agent automatic settings')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc18-compatible-auto-suggestions'), 'Cumulative checks must retain RC18 compatible automatic suggestions')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc18-model-error-remediation'), 'Cumulative checks must retain RC18 actionable model errors')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc18-release-mobile-smoke'), 'Cumulative checks must retain RC18 release smoke coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc17-review-consolidation'), 'Cumulative checks must retain RC17 review consolidation')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc17-model-details-persistence'), 'Cumulative checks must retain RC17 suggestion disclosure')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc17-auto-model-selection'), 'Cumulative checks must retain RC17 automatic model selection')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc17-secret-test-guidance'), 'Cumulative checks must retain RC17 secret test guidance')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc17-release-mobile-smoke'), 'Cumulative checks must retain RC17 release smoke coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc16-agent-create-model-suggestion'), 'Cumulative checks must retain RC16 creation-time model suggestions')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc16-model-priority'), 'Cumulative checks must retain RC16 model priority controls')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc16-existing-agent-model-suggestion'), 'Cumulative checks must retain RC16 existing-agent suggestions')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc16-model-change-confirmation'), 'Cumulative checks must retain RC16 explicit model confirmation')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc16-release-mobile-smoke'), 'Cumulative checks must retain RC16 release smoke coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc15-builder-scoring'), 'Cumulative checks must retain RC15 Builder scoring')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc15-agent-scoring'), 'Cumulative checks must retain RC15 agent scoring')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc15-plugin-scoring'), 'Cumulative checks must retain RC15 plugin scoring')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc15-security-export-regression'), 'Cumulative checks must retain RC15 security coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc14-sidebar-order'), 'Cumulative checks must retain restored sidebar order coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc14-plugin-collapse-persistence'), 'Cumulative checks must retain plugin collapse persistence')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc13-mail-partner-visibility'), 'Cumulative checks must retain upgraded partner visibility')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc13-gmail-oauth'), 'Cumulative checks must retain Gmail OAuth lifecycle')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc13-microsoft-oauth'), 'Cumulative checks must retain Microsoft OAuth lifecycle')
assert(previousChecklist?.items.some((item: any) => item.id === 'plugin-layout-views'), 'Cumulative 2.0 checks must cover every plugin view')
assert(previousChecklist?.items.some((item: any) => item.id === 'guardrail-create-target'), 'Cumulative 2.0 checks must cover guardrail targeting')
assert(previousChecklist?.items.some((item: any) => item.id === 'eval-create-run'), 'Cumulative 2.0 checks must cover eval runs')
assert(previousChecklist?.items.some((item: any) => item.id === 'optimize-skeleton'), 'Cumulative 2.0 checks must retain historical Optimize coverage')
assert(
  previousChecklist?.items.find((item: any) => item.id === 'plugin-sidebar-mobile')?.fields.verifiedBy?.some((entry: string) => entry.includes('Max') && entry.includes('local Dev')),
  'Imported RC4/RC5 navigation verification must retain reviewer and environment provenance',
)
assert(
  previousChecklist?.items.filter((item: any) => item.id.startsWith('rc18-')).every((item: any) => (
    item.fields.verifiedBy?.some((entry: string) => entry.includes('Max') && entry.includes('local Dev'))
  )),
  'Max local RC18 results must remain as prior verification without pre-completing another tester copy',
)
assert(stableChecklist?.items.some((item: any) => item.id === 'secret-runtime-redaction'), 'Stable regression checks must retain secret redaction coverage')
assert(stableChecklist?.items.some((item: any) => item.id === 'openrouter-provider'), 'Stable regression checks must retain OpenRouter coverage')
assert(stableChecklist?.items.some((item: any) => item.id === 'xai-provider'), 'Stable regression checks must retain xAI coverage')
assert(pageSource.includes('const isChecklist = Boolean(groupField && checkField)'), 'Checklist presentation must be manifest-driven')
assert(pageSource.includes('Start {release} checklist'), 'Review page must initialize a release with one clear action')
assert(pageSource.includes('function ChecklistItemRow'), 'Review page must render checklist rows instead of template cards')
assert(pageSource.includes("{notes ? 'Edit notes' : 'Add notes'}"), 'Checklist rows must expose note editing directly')
assert(pageSource.includes('aria-label="Release checklists"'), 'Review page must expose release tabs accessibly')
assert(pageSource.includes('const toggleCheck = async'), 'Review page must persist direct checkbox changes')
assert(pageSource.includes('isChecklist ? ('), 'Checklist suggestions must not use the generic card catalog')
assert(pageSource.includes('const setChecklistOutcome = async'), 'Review page must persist explicit pass and fail outcomes')
assert(pageSource.includes('aria-label={`Mark ${item.name} failed`}'), 'Checklist rows must expose a direct accessible fail action')
assert(pageSource.includes("outcome === 'failed'"), 'Failed checks must have a distinct visual state')
assert(pageSource.includes("completed ? 'line-through"), 'Completed checks must be crossed out')
assert(pageSource.includes(": notes\n          ? 'bg-yellow"), 'Commented pending checks must be highlighted')
assert(pageSource.includes('w-full min-w-0 max-w-7xl overflow-x-hidden'), 'Plugin pages must constrain narrow-screen horizontal overflow')
assert(pageSource.includes('w-full min-w-0 max-w-full overflow-hidden rounded-lg border border-sky-200'), 'Suggested cards must shrink within phone viewports')
assert(pageSource.includes('grid w-full min-w-0 grid-cols-4'), 'Plugin view controls must use four equal phone-width tracks')
assert(/grid w-full min-w-0[^"']*grid-cols-3/.test(pageSource), 'Plugin collection tabs must use three equal phone-width tracks')
assert(pageSource.includes('Export release review'), 'Review actions must expose a release report export')
assert(pageSource.includes('Archive release checklist'), 'Review actions must expose release-level archiving')
assert(pageSource.includes('Restore release checklist'), 'Review actions must expose release-level restoration')
assert(pageSource.includes('getSupersededReviewReleaseIdsToArchive'), 'Starting a focused checklist must move every superseded release out of the active queue')
assert(pageSource.includes('planReviewReleaseConsolidation'), 'Review must consolidate separately persisted legacy RC sets')
assert(pageSource.includes('collectRecentRuntimeErrors'), 'Review exports must collect recent runtime errors')
assert(pageSource.includes('Reviewer name'), 'Review export must identify the reviewer')
assert(pageSource.includes('resolveReviewIdentity(user'), 'Review export must prefill identity from the authenticated user or browser fallback')
assert(pageSource.includes("kind === 'onprem' ? 'On-prem'"), 'Review export must identify local, cloud, and on-prem environments')
assert(pageSource.includes("item.description.match(/^Test:"), 'Review rows must separate actions from expected pass results')
assert(pageSource.includes('[overflow-wrap:anywhere]'), 'Review instructions and notes must wrap long evidence safely on narrow screens')
assert(pageSource.includes('Previously verified by {verifiedBy.join'), 'Review rows must identify aggregated prior confirmations')
assert(pageSource.includes("return ['1.9.9', '2.0.0', '2.0.0-test-rc45'].filter"), 'Review filters must stay limited to the three release families')

console.log('PluginReviewChecklist.test.ts: 96 tests passed')
